#!/bin/sh

version=1.0
version_date=23_0804

hmLib9_print_data_model()
{
    CC=gcc
    basename=___temp___

    cat <<__EOF__ > $basename.c
#include <stdio.h>
int main( void )
{
    char *ptr  = (char *) 0;
    int isize  = sizeof(int);
    int lsize  = sizeof(long);
    int llsize = sizeof(long long);
    int psize  = sizeof(ptr);

    printf( "/*                                                     \r\n" );
    printf( " * (C) 2023  Hongman Ko                                \r\n" );
    printf( " *                                                     \r\n" );
    printf( " * Automatically generated by                          \r\n" );
    printf( " * hmLib9_print_data_model.sh version $version ($version_date)\r\n" );
    printf( " */                                                    \r\n" );
    printf( "                                                       \r\n" );
    printf( "/*                                                     \r\n" );
    printf( " * Probed Data Model:                                  \r\n" );
    printf( " *   > sizeof(int)       = %d                          \r\n", isize  );
    printf( " *   > sizeof(long)      = %d                          \r\n", lsize  );
    printf( " *   > sizeof(long long) = %d                          \r\n", llsize );
    printf( " *   > sizeof(pointer)   = %d                          \r\n", psize  );
    printf( " */                                                    \r\n" );
    printf( "                                                       \r\n" );
    printf( "#if (0)                                                \r\n" );
    printf( "  #define HMLIB9_DATA_MODEL_UNK   (0x0   )                \r\n" );
    printf( "  #define HMLIB9_DATA_MODEL_LP32  (0x0001)                \r\n" );
    printf( "  #define HMLIB9_DATA_MODEL_ILP32 (0x0002)  /* Linux 32-bit, Windows win32 */    \r\n" );
    printf( "  #define HMLIB9_DATA_MODEL_LLP64 (0x0010)  /* Windows 64-bit */                 \r\n" );
    printf( "  #define HMLIB9_DATA_MODEL_LP64  (0x0020)  /* Linux 64-bit, cygwin64 */         \r\n" );
    printf( "  #define HMLIB9_DATA_MODEL_ILP64 (0x0040)                \r\n" );
    printf( "#endif                                                 \r\n" );
    printf( "                                                       \r\n" );

    if(      isize==4    && lsize==4    && llsize==8    && psize==4 ) printf( "#define HMLIB9_DATA_MODEL  HMLIB9_DATA_MODEL_ILP32" );
    else if( isize==4    && lsize==4    && llsize==8    && psize==8 ) printf( "#define HMLIB9_DATA_MODEL  HMLIB9_DATA_MODEL_LLP64" );
    else if( isize==4    && lsize==8    && llsize==8    && psize==8 ) printf( "#define HMLIB9_DATA_MODEL  HMLIB9_DATA_MODEL_LP64"  );
    else if( isize==8    && lsize==8    && llsize==8    && psize==8 ) printf( "#define HMLIB9_DATA_MODEL  HMLIB9_DATA_MODEL_ILP64" );
    else                                                              printf( "#define HMLIB9_DATA_MODEL  HMLIB9_DATA_MODEL_UNK"   );
    printf( "\r\n" );

    return 0;
}
__EOF__

    head_file=___hmLib9_data_model___.h

    echo
    uname -a
    echo
    $CC --version
    $CC -o $basename $basename.c
    echo -n -e "\e[33;1m"
    ./$basename > $head_file
    cat $head_file
    echo -e "\e[m"

    rm -f $basename $basename.c
}

arg1=$1
if [ "$arg1" = "print" ]; then
    hmLib9_print_data_model
fi
